#!/bin/sh
set -e

usage() {
    echo "usage: $0 COMMAND"
    echo
    echo "install php helper."
    echo
    echo "Commands:"
    echo "   init  install php extension."
    echo
}

case "$1" in
    init)
        echo $PHPIZE_DEPS
        apk add --no-cache --virtual .phpize-deps $PHPIZE_DEPS
        pecl install igbinary
        printf "yes\nyes\n" | pecl install redis
        pecl install rdkafka
        rm -rf /tmp/pear
        apk del .phpize-deps
        docker-php-ext-enable igbinary redis rdkafka
        ;;
    nginx)
        echo 'nginx'
        mv /tmp/src/dynamic.conf /etc/nginx/conf.d/dynamic.conf.bak
        mv /tmp/src/index.php /var/www/html
        sed -i "s/80/81/g" /etc/nginx/conf.d/default.conf
        ;;
    start)
        echo 'start'
        cp /etc/nginx/conf.d/dynamic.conf.bak /etc/nginx/conf.d/dynamic.conf
        sed -i "s/view/${site}/g" /etc/nginx/conf.d/dynamic.conf
        mkdir -p /run/nginx/ /opt/aha/${site}/public
        cp /var/www/html/index.php /opt/aha/${site}/public
        nohup php-fpm > /dev/null 2>&1 &
        nginx -g "daemon off;"
        ;;
    clear)
        echo 'clear'
        ;;
    *)
        usage
        exit 1
        ;;
esac